#!/usr/bin/env python3
"""
generate_constants.py - Export constants from constants.py to shell format

This script generates a shell script that defines all constants needed by
repo2notebook-wrapper.sh. It ensures that the Python and shell versions
stay synchronized.
"""

import sys
from pathlib import Path

# Ensure we can import constants from the same directory
script_dir = Path(__file__).parent.resolve()
sys.path.insert(0, str(script_dir))

try:
    from constants import (
        MAX_FILE_COUNT,
        MAX_TOTAL_SIZE_MB,
        MAX_SINGLE_FILE_MB,
        DEFAULT_TOKEN_RATIO,
        BINARY_EXTENSIONS,
        SENSITIVE_PATTERNS,
        DEFAULT_EXCLUDE_PATTERNS,
        ALWAYS_EXCLUDE_FILES,
        DEFAULT_EXCLUDE_DIRS,
        OUTPUT_DIR,
        MAX_WORDS_PER_FILE,
    )
except ImportError as e:
    print(f"Error: failed to import constants: {e}", file=sys.stderr)
    sys.exit(1)


def sh_escape(s):
    """Escape a string for safe inclusion in double-quoted shell string."""
    # Replace backslashes and double quotes
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    return s


def format_array(items):
    """Format a list of items as a bash array with proper quoting."""
    quoted = []
    for item in items:
        # Escape special characters
        escaped = sh_escape(str(item))
        quoted.append(f'"{escaped}"')
    return '(' + ' '.join(quoted) + ')'


# Output shell variable assignments
print(f"# Auto-generated constants - DO NOT EDIT")
print(f"# Generated by generate_constants.py")
print()

# Core limits
print(f"MAX_FILE_COUNT={MAX_FILE_COUNT}")
print(f"MAX_TOTAL_SIZE_MB={MAX_TOTAL_SIZE_MB}")
print(f"MAX_SINGLE_FILE_MB={MAX_SINGLE_FILE_MB}")
print(f"DEFAULT_TOKEN_RATIO={DEFAULT_TOKEN_RATIO}")
print(f"MAX_WORDS={MAX_WORDS_PER_FILE}")  # Alias for wrapper compatibility
print(f"OUTPUT_DIR={sh_escape(OUTPUT_DIR)}")
print()

# Arrays
print(f"BINARY_EXTENSIONS={format_array(BINARY_EXTENSIONS)}")
print(f"SENSITIVE_PATTERNS={format_array(SENSITIVE_PATTERNS)}")
print(f"DEFAULT_EXCLUDE_PATTERNS={format_array(DEFAULT_EXCLUDE_PATTERNS)}")
print(f"DEFAULT_EXCLUDE_FILES={format_array(ALWAYS_EXCLUDE_FILES)}")
print(f"DEFAULT_EXCLUDE_DIRS={format_array(DEFAULT_EXCLUDE_DIRS)}")

# Success indicator
print("CONSTANTS_LOADED=true")
